name: Terraform Plan
on: pull_request

jobs:
  plan:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRETA_ACCESS_KEY: ${{secrets.AWS_SECRETA_ACCESS_KEY}}
      AWS_REGION: "eu-west-2"
    

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::123456789100:role/my-github-actions-role
          aws-region: us-east-2
          
      - name: Initialise Terraform
        run: terraform init -input=false
    
      - name: Terraform Plan
        run: terraform plan -input=false
        
