name: Terraform Plan
on: pull_request
      
jobs:
    plan:
      runs-on: ubuntu-latest
    
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Install doctl
          uses: digitalocean/action-doctl@v2
          with:
            token: secrets.DOGITALOCEAN_ACCESS_TOKEN
          
        - name: Install Terraform
          uses: hashicorp/setup-terraform@v3
          with:
            terraform_version: latest 
        
        - name: Terraform fmt
          run: terraform fmt -check

        - name: Terraform init
          run: terraform init -input=false

        - name: Terraform Plan
          run: terraform plan 
              
          


  



