name: view Terraform plan
on: pull_request
jobs: 
    plan: 
        runs-on: ubuntu-latest
        env:
            AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
            AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

        steps: 
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install Terraform
              uses: hashicorp/setup-terraform@v2
              with:
                terraform_version: latest
            - name: Configure AWS credentials
              run: |
                mkdir -p ~/.aws
                echo "[default]" > ~/.aws/credentials
                echo "aws_access_key_id = $AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
                echo "aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
        
            - name: Initialise Terraform
              run: terraform init -input=false

            - name: Terraform plan
              run: terraform plan -input=false

        
